### ISSUE TITLE
Micronaut GCP Features MVP Roadmap

### ISSUE THREAD

**Issue by saturnism** [micronaut-projects/micronaut-gcp#1]
- [x] Consistent credentials (#2)
- [x] Trace (#2)
- [x] Logging w/ API and/or JSON format (https://github.com/micronaut-projects/micronaut-gcp/pull/236)

Recommend additional integration support
- [x] Pub/Sub (#173)

**Comment by graemerocher** [comment]
@saturnism for logging, I noticed Spring Cloud GCP has a lot more stuff around logback layouts etc. in the sources as well as some integration with MDC / trace ID etc. Do we need equivalents in Micronaut?

**Comment by davinkevin** [comment]
From my point of view, the log format is important and allow a smooth integration between distributed traces and logs involved in requests. 

This is, for now, the main reason we are staying in the spring ecosystem (but we would like to try something else to reduce memory consumption in K8S).

**Comment by kamilgregorczyk** [comment]
I'd also add stackdriver metrics to the roadmap

**Comment by graemerocher** [comment]
This PR includes Stackdriver Metrics support https://github.com/micronaut-projects/micronaut-micrometer/pull/18

**Comment by graemerocher** [comment]
@saturnism can you provide the references to the log format that the Spring support uses that we should ship with again?

**Comment by davinkevin** [comment]
I used the implementation from spring for "reverse engineering" the log format

> https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/src/main/resources/org/springframework/cloud/gcp/autoconfigure/logging/logback-json-appender.xml
> https://github.com/spring-cloud/spring-cloud-gcp/blob/05fdf30ed34425ed6cf064923e40fe5922fe39e4/spring-cloud-gcp-logging/src/main/java/org/springframework/cloud/gcp/logging/StackdriverJsonLayout.java

The official documentation describing the logEntry is available here: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry

**Comment by saturnism** [comment]
eak, missed the github notifications. we should be able to re-use the same layout and include the trace id in the right fields.  there are also 2 different appenders that we can use: the Json one, and straight to Stackdriver Logging API.

**Comment by alvarosanchez** [comment]
@graemerocher can this be closed?

**Comment by graemerocher** [comment]
the log format stuff is  missing

**Comment by graemerocher** [comment]
Updated progress on this uber-issue. Thanks @viniciusccarvalho !

**Comment by davinkevin** [comment]
For information, the PR about logging and JSON is https://github.com/micronaut-projects/micronaut-gcp/pull/236 and not the #237 like described in the original issue. 

Thanks again to @viniciusccarvalho

**Comment by saturnism** [comment]
Thanks @viniciusccarvalho !

**Comment by saturnism** [comment]
I feel we can close this initial issue and track additional support separately.
