### ISSUE TITLE
Google library discrepancies causing conflicts

### ISSUE THREAD

**Issue by turneand** [micronaut-projects/micronaut-gcp#1046]
### Expected Behavior

Applications depending on multiple micronaut-gcp components should work together seamlessly

### Actual Behaviour

Having compatibility issues when running multiple micronaut gcp libraries, including tracing, logging, pubsub, cloudsql (especially if we also bringing in cloud-sql-connector-r2dbc-postgres, but that's beyond the scope here I think).

Specific example, incompatible gax libraries (gax seems to be the cause of most of these issues)

- micronaut-gcp-logging:5.4.0 -> micronaut-gcp-common:5.4.0 -> google-cloud-core:2.31.0 -> gax:2.41.0
- micronaut-gcp-secret-manager:5.4.0 -> google-cloud-secretmanager:2.33.0 -> gax:2.39.0 & gax-grpc:2.39.0 & gax-httpjson:2.39.0

Issue above is that if gax:2.41.0 is "chosen", then it doesn't work correctly with gax-grpc:2.39.0, and we get errors like:

```
[ERROR] TestApp.simpleTest -- Time elapsed: 1.609 s <<< ERROR!
java.lang.AbstractMethodError: Receiver class com.google.api.gax.grpc.GrpcCallContext does not define or inherit an implementation of the resolved method 'abstract com.google.api.gax.rpc.ApiCallContext withEndpointContext(com.google.api.gax.rpc.EndpointContext)' of interface com.google.api.gax.rpc.ApiCallContext.
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:233)
        at com.google.cloud.secretmanager.v1.stub.GrpcSecretManagerServiceStub.create(GrpcSecretManagerServiceStub.java:248)
        at com.google.cloud.secretmanager.v1.stub.SecretManagerServiceStubSettings.createStub(SecretManagerServiceStubSettings.java:349)
        at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.<init>(SecretManagerServiceClient.java:452)
        at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.create(SecretManagerServiceClient.java:434)
        at TestApp.simpleTest(TestApp.java:17)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

We did also look into seeing whether the google bom's could be used, but I'm guessing they were not used for compatibility reasons with the rest of micronaut?

Note, that within our maven setup, we had some secret-manager logic in a "common" library, which meant the dependency resolution for gax through logging and our separate project ended up being at the same depth in the dependency tree, resulting in the first-defined to "win".

Not 100% sure on why  micronaut-gcp-logging needs micronaut-gcp-common, excluding this dependency doesn't seem to cause any issues yet (although not tested much).  Although can also explicitly define the gax versions, or exclude gax from micronaut-logging (this is the same approach we've adopted for the cloudsql libraries)

### Steps To Reproduce

1. Run the build for the linked github project
2. This will build a multi-module maven build replicating a project setup that exhibits the dependency issues
3. You can also view the dependency tree to see the hierarchy as defined above

### Environment Information

Windows / unix
Java 17

### Example Application

https://github.com/turneand/micronaut-gcp-dependency-issue

### Version

4.3.1

**Comment by wetted** [comment]
@tunreand This conflict is fixed in the next minor release `micronaut-gcp:5.5.0` where the solution uses: `google-cloud-core:2.33.0` and `google-cloud-secretmanager:2.35.0`.

In the meantime I think you can try adding the following to your project parent pom as a workaround (just the `google-cloud-secretmanager` dependency might be enough):

```xml
  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-secretmanager</artifactId>
      <version>2.35.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-core</artifactId>
      <version>2.33.0</version>
    </dependency>
  </dependencies>

```

**Comment by turneand** [comment]
Thanks @wetted , we've had a few issues recently with various gcp libraries that required direct upgrades so have hit this a fair bit, with Google teams pushing for their bom to be included, but that leads to all sorts of other problems when using a management framework such as micronaut.
