### ISSUE TITLE
com.google.cloud:google-cloud-pubsub (version 1.126.1) does not honour message ordering

### ISSUE THREAD

**Issue by abclabs-jon** [micronaut-projects/micronaut-gcp#1095]
### Expected Behavior

Messages published with an ordering key to a single region should be handled in order for subscriptions with message ordering enabled.

### Actual Behaviour

After upgrading Micronaut from 3.8.10 to 4.3.7, subscribers started receiving messages out of order.

The root cause seems to be in com.google.cloud:google-cloud-pubsub: https://github.com/googleapis/java-pubsub/issues/1889

io.micronaut.gcp:micronaut-gcp-pubsub:5.4.1 uses com.google.cloud:google-cloud-pubsub:1.126.1, which has the bug. Forcing an upgrade of that solved the issue for us:

```
    constraints {
        implementation("com.google.cloud:google-cloud-pubsub:1.127+") {
            because("https://github.com/googleapis/java-pubsub/issues/1889")
        }
    }
```

### Steps To Reproduce

See https://github.com/googleapis/java-pubsub/issues/1889

### Version

4.3.7

**Comment by turneand** [comment]
This should already be resolved in micronaut-platform 4.4.0, which brings in micronaut-gcp-pubsub 5.5.0, which brings in google-cloud-pubsub 1.128.0, which contains the fix for this issue.
