### ISSUE TITLE
StackdriverJsonLayout Does not handle TRACE Logs Appropriately

### ISSUE THREAD

**Issue by jjathman** [micronaut-projects/micronaut-gcp#1130]
### Expected Behavior

Writing a `trace` level log entry should be possible within GCP and it should be viewable in the log viewer.

### Actual Behaviour

These entries seem to be silently discarded, I believe due to the invalid SEVERITY of TRACE being sent.

### Steps To Reproduce

Within a GCP application (Cloud Run in my case) attempt to write a log entry with a level of TRACE using the standard Micronaut GCP Stackdriver logging. It will not show up within the log viewer.

According to [this](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#LogSeverity) from Google:

> If you are writing log entries, you should map other severity encodings to one of these standard levels. For example, you might map all of Java's FINE, FINER, and FINEST levels to LogSeverity.DEBUG. You can preserve the original severity level in the log entry payload if you wish.

I believe `trace` logs should be translated into `debug` logs within the `StackdriverJsonLayout` class. I think an implementation example is what [Spring Cloud does for this](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/StackdriverJsonLayout.java#L48-L55). It appears as though Micronaut GCP simply sends the log level directly through to the JSON output, which won't always be an allowed value.

### Version

Micronaut GCP version 5.4.1

**Comment by graemerocher** [comment]
seems you identified the issue, could you send a PR?

**Comment by jjathman** [comment]
@graemerocher yep I should be able to do that. Just wanted to make sure I wasn't missing something obvious.

**Comment by jjathman** [comment]
@graemerocher PR ready for review.

**Comment by jjathman** [comment]
@graemerocher OK I created a new PR that fixes the author issue.
