### ISSUE TITLE
All Spans being wrapped into get /health when using Cloud Endpoints + K8S

### ISSUE THREAD

**Issue by jacobmims** [micronaut-projects/micronaut-gcp#15]
I followed the docs here and in Micronaut Core to annotate my API for Stackdriver Tracing. Whenever executing locally, I'm tracing what I expect (ie., the top level span is the request to the endpoint, with the request processing nested under it). However, when deployed, the behavior is dramatically different. 

Our environment uses Cloud Endpoints to act as an edge for our Kubernetes Cluster. Whenever a request goes through Cloud Endpoints to hit our API, our spans end up acting very strangely. Our healthcheck tracing acts as expected, with a new trace coming in every few seconds, but all of our calls to the service do not emit for a lengthy period of time (ie., several minutes), and when it finally flushes to Stackdriver, we end up with a bunch of spans all nested under one of our health check traces.

This could be a configuration issue on my end, but I have followed the docs as written. In our `application.yml` for our testing environment I have
```
tracing:
  zipkin:
    enabled: true
    traceId128Bit: true
    sampler:
      probability: 1.0
```

All of the exposed endpoints from our controller are annotated with `@NewSpan` with other spans declared throughout the code. Again, when testing this locally and pointing at our test Stackdriver, this works as expected. I don't have traces on hand to show the issue, because it's exceedingly difficult to grab one that has our nested spans, since they hide in the middle of dozens of normal healthcheck traces, and I've had to disable tracing for the time being, so I don't have fresh data. 

If there is additional information that I can provide, please let me know, and I will do my best to do so.

**Comment by graemerocher** [comment]
@saturnism Do you know of any production issues with Stackdriver Trace that have show similar behaviour?

**Comment by jacobmims** [comment]
FYI, I was able to get this feature working by disabling tracing from Micronaut GCP and just wiring my Zipkin traces to a [mini-server container sidecar](https://github.com/openzipkin/zipkin-gcp) with no other changes.

**Comment by graemerocher** [comment]
I believe this duplicates https://github.com/micronaut-projects/micronaut-core/issues/2126
