### ISSUE TITLE
Document running raw functions locally

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-gcp#171]
If it isn't possible, it should say so in the docs.

**Comment by graemerocher** [comment]
Raw functions you don't really run since there is no server. You simple instantiate the function using `new MyFunction()` in a test and execute the method that would handle the function

**Comment by jameskleeh** [comment]
@graemerocher Makes sense to me, but the docs don't have any mention about it so I think it would be good to explicitly state that
