### ISSUE TITLE
CORS Filter does not work

### ISSUE THREAD

**Issue by tkgreg** [micronaut-projects/micronaut-gcp#180]
### Steps to Reproduce

1. Using the demo archive run task `runFunction`[demo.zip](https://github.com/micronaut-projects/micronaut-gcp/files/4981489/demo.zip)
2. Create a preflight request like:
```
OPTIONS http://localhost:8080/hello/post
Access-Control-Request-Method: POST
Access-Control-Request-Headers: origin, x-requested-with
Origin: http://localhost:3000

```

### Expected Behaviour

I expect to get an answer from `CorsFilter`, because I enabled it in `application.yml`. I also expect that my `HelloFilter` will be called because it has uri pattern `/**` 

### Actual Behaviour

Currently, it returns `404` response and no trace in logs about `HelloFilter`

### Environment Information

- **Operating System**: MacOS 10.15.6
- **Micronaut Version:** 2.0.0
- **JDK Version:** 11

### Example Application

- I attached an archive with my sample project

**Comment by graemerocher** [comment]
I believe this duplicates https://github.com/micronaut-projects/micronaut-servlet/issues/31

Please try use 2.0.1 of `micronaut-servlet-core` and see if that resolves your problem.

**Comment by tkgreg** [comment]
Yeah it works! But you do not have 2.0.1 you have only 1.0.1 version.

**Comment by graemerocher** [comment]
Sorry I meant 1.0.1
