### ISSUE TITLE
Feature Request: Add Google Secret Manager support

### ISSUE THREAD

**Issue by viniciusccarvalho** [micronaut-projects/micronaut-gcp#241]
Just a placeholder, I'm volunteering for this :)

**Comment by viniciusccarvalho** [comment]
@graemerocher @jameskleeh I could use some of your knowledge designing this. I'll write down some design choices and please chime in:

1. Make it a distributed config client such as vault/consul, be consistent with the framework

2. SM is limited when compared to those products as it only offer a flat hierarchy, so things like `/config/application/foo.bar` would not work. SM however does have the concept of labels which I think it could help us on choosing certain things, here's an idea.

Just like AWS parameter store we need to rely on env qualifiers such as `application_$env`

Here's a novel idea: the choice of using KV or file could be done per entry instead of being global, by using a label:

| Secret Name | label | description |
|---|---|---|
| application | type:yaml | all apps load the contents of this file |
| application_prod | type: properties | all prod environment apps |
| my-micronaut-app | type: json | Application specific json format |
| dbPassword_prod | | all apps in prod read this value |
| dbPassword_test | | all apps in test read this value|

The flat nature is unfortunate and would not allow users to have something like `/config/backend/application` and `config/frontend/application`. To make things worse, secrets must be unique so not even using labels would allow us to differentiate between an `application` file for different groups of applications.

Let me know your thoughts and I can wrap up development of the feature

**Comment by jameskleeh** [comment]
@viniciusccarvalho In general the proposal makes sense to me. It should be a distributed configuration client. Given the flat hierarchy limitation, using `application_$env` makes sense. Regarding the usage of labels, seems OK. I would prefer multiple labels like `file`, `yaml` if multiple labels are supported so we don't have to create some custom structure that needs to be documented and implemented.

**Comment by alvarosanchez** [comment]
Fixed via #324
