### ISSUE TITLE
Feature request: Configure pubsub topics and subuscriptions through properties files

### ISSUE THREAD

**Issue by robertomoreno** [micronaut-projects/micronaut-gcp#326]
Sorry if this feature is already possible but I couldn't found how to implement this and it is stopping us to migrate to Micronaut.

### Suggested improvement

Currently we can configure subscriptions and topics through the `@Subscription()` and `@Topic()` annotations. Problem is that this force us to hardcode the names as Java constants. An Improvement for us would be to configure the names based on properties files or environment variables. Something like:

```java
@Subscription(configuration = "foo")
public void onMessage(PubsubMessage foo) {
//....
}
```
And in properties just:

```yaml
gcp:
  pubsub:
    subscriber:
      foo:
        subscriptionName: "staging-foo"
        //....
```

### Why?

Having 2 or more GCP projects configured, each of these could have several environments which is a common scenario working with cloud providers:

- live: Production and Staging...
- nonlive: Developement, Test, feature environments...
- developers environments...

Subscription names could be like "{environment}-subscriptionName" to avoid name clashes, similar for topics. So it is not really an option to hardcode the names in a mature infrastructure. As a workaround, it is possible to setup multiple similar Listener classes that builds based on Micronaut Environments but, aside of code duplication, it does not work for non discrete environments (as feature environments)

Other potential benefits are:
- Better conciliation between infrastructure and business code. Ideally the java app should not care about what topic it is pushing messages, a property file could be generated by orchestrators as Ansible.
- Quicker switch between topics publishing/subscription subscribe since it is only require to change the property file and restart the app. No need of recompile + ci/cd sacraments
- Better integration/functional testing. If listeners/subscribers can be injected with different topics configured and created on the fly, tests can easily be parallelized.

**Comment by Steven-M-Brown** [comment]
I believe you can do something like this:
`@Subscription(value = "${ENVIRONMENT_VARIABLE:`default`}")`

Would that accomplish what you are after?

**Comment by robertomoreno** [comment]
Indeed, it does. Thanks a lot. Closing the issue.
