### ISSUE TITLE
When are new releases published?

### ISSUE THREAD

**Issue by oscarfh** [micronaut-projects/micronaut-gcp#48]
Hi,
I found out about this project yesterday and I would love to use it in my project. But we use Micronaut 1.2.x and the released version of this project (1.0.0) is not compatible with it due to the upgrade from zipkin (Micronaut 1.2 uses Zipkin 2.15.x while this project expects 2.7.15, which contains a -test.jar that was remove in version 2.14.x)
I came here today to make a PR for this lib version upgrade, but I saw that something similar is already in place. But there is no release published with these changes.

Is there any plan to do so? 

Thanks a lot,
Oscar

**Comment by graemerocher** [comment]
Will do a release soon. Thanks

**Comment by graemerocher** [comment]
1.1.0 has been published now. Thanks
