### ISSUE TITLE
GCP function http doesn't support micronaut-serialization

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-gcp#724]
If you follow the instructions to add micronaut-serialization to a gcp-function project, it fails to run as the [beans in the jackson package](https://github.com/micronaut-projects/micronaut-gcp/tree/master/gcp-function-http/src/main/java/io/micronaut/gcp/function/http/jackson) expect JacksonConfiguration and other classes to exist on the classpath (but as per instructions, we replace the jackson library with our own)

**Comment by graemerocher** [comment]
The type is question https://github.com/micronaut-projects/micronaut-gcp/blob/master/gcp-function-http/src/main/java/io/micronaut/gcp/function/http/jackson/GoogleJacksonConfiguration.java is redundant and can just be deleted

**Comment by timyates** [comment]
@graemerocher But what about https://github.com/micronaut-projects/micronaut-gcp/blob/master/gcp-function-http/src/main/java/io/micronaut/gcp/function/http/jackson/ObjectMapperCustomizer.java?

**Comment by sdelamo** [comment]
I assume this is solved in Micronaut Framework 4 right @timyates ?

**Comment by timyates** [comment]
Tested this for 4.0.4 by enabling the combination in https://github.com/micronaut-projects/micronaut-starter/pull/2004 and then running

```
./gradlew micronaut-cli:run --args="create-app --build=gradle --jdk=17 --lang=java --test=junit --features=google-cloud-function,serialization-jackson com.example.demo"
```

All worked as expected.  I'll close this as we have the PR now
