### ISSUE TITLE
uncouple the module from jackson-databind and use serde instead

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-gcp#751]
### Issue description

We are using in multiple instances 

`implementation(mn.micronaut.jackson.databind)`

**Comment by debrutal** [comment]
We were also surprised by having jackson as an implicit serializer. 
[JsonPubSubMessageSerDes](https://micronaut-projects.github.io/micronaut-gcp/latest/api/io/micronaut/gcp/pubsub/serdes/JsonPubSubMessageSerDes.html) is not using our configured micronaut serde configuration. 

Therefor our [serde-configuration](https://micronaut-projects.github.io/micronaut-serialization/1.0.0-M5/guide/configurationreference.html#io.micronaut.serde.config.SerdeConfiguration) is not respected when using `write-dates-as-timestamp=false`.
