### ISSUE TITLE
Add documentation for configuring GPC library logging.

### ISSUE THREAD

**Issue by jeremyg484** [micronaut-projects/micronaut-gcp#943]
### Feature description

The GPC libraries use Java Util Logging internally and are by default configured to only log errors and warnings. When developing Micronaut GCP applications, it can be useful at times to configure GCP logging at a more detailed level. 

There is a bridge library that enables configuring this in logback, but it requires some extra setup, and is recommended to not be used by default as it negatively affects logging performance.

Documentation should be added that explains this and shows how to set up the extra logging at development time.

**Comment by sdelamo** [comment]
@jeremyg484 please give priority to this.
